etcd_ca_conf_directory: "{{ '~/etcd-certs' | expanduser }}"

etcd_version: "3.3.18"
etcd_client_port: "2379"
etcd_peer_port: "2380"
etcd_interface: "ens5"
etcd_conf_dir: "/etc/etcd/certs"
etcd_download_dir: "/opt/etcd"
etcd_bin_dir: "/usr/local/bin"
etcd_data_dir: "/var/lib/etcd"

etcd_settings:
"ETCD_NAME": "{{ansible_hostname}}"
"ETCD_CERT_FILE": "{{etcd_conf_dir}}/cert-etcd.pem"
"ETCD_KEY_FILE": "{{etcd_conf_dir}}/cert-etcd-key.pem"
"ETCD_PEER_CERT_FILE": "{{etcd_conf_dir}}/cert-etcd.pem"
"ETCD_PEER_KEY_FILE": "{{etcd_conf_dir}}/cert-etcd-key.pem"
"ETCD_PEER_TRUSTED_CA_FILE": "{{etcd_conf_dir}}/ca-etcd.pem"
"ETCD_PEER_CLIENT_CERT_AUTH": "true"
"ETCD_CLIENT_CERT_AUTH": "true"
"ETCD_TRUSTED_CA_FILE": "{{etcd_conf_dir}}/ca-etcd.pem"
"ETCD_ADVERTISE_CLIENT_URLS": "{{'https://' + hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address + ':' + etcd_client_port}}"
"ETCD_INITIAL_ADVERTISE_PEER_URLS": "{{'https://' + hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address + ':' + etcd_peer_port}}"
"ETCD_LISTEN_PEER_URLS": "{{'https://' + hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address + ':' + etcd_peer_port}}"
"ETCD_LISTEN_CLIENT_URLS": "{{'https://' + hostvars[inventory_hostname]['ansible_' + etcd_interface].ipv4.address + ':' + etcd_client_port}}"
"ETCD_INITIAL_CLUSTER_STATE": "new" 
"ETCD_DATA_DIR": "{{etcd_data_dir}}"
"ETCD_AUTO_COMPACTION_RETENTION": "0"
"ETCD_SNAPSHOT_COUNT": "100000"
"ETCD_HEARTBEAT_INTERVAL": "100"
"ETCD_ELECTION_TIMEOUT": "1000"
"ETCD_MAX_SNAPSHOTS": "5"
"ETCD_MAX_WAL": "5"

